import { readFileSync } from 'node:fs';
import path from 'node:path';
import { describe, expect, it } from 'vitest';

// The platformer lives in a self-contained HTML file. Its stage/level table is
// generated by a pure, DOM-free region marked with the comments below, so we can
// extract and evaluate just that region to test the generation invariants.
const htmlPath = path.resolve(
  process.cwd(),
  'public/game/jump_and_run_v2.html',
);
const html = readFileSync(htmlPath, 'utf8');

const START = '/*__LEVELS_GEN_START__*/';
const END = '/*__LEVELS_GEN_END__*/';

function extractGenerated() {
  const from = html.indexOf(START);
  const to = html.indexOf(END);
  expect(from).toBeGreaterThan(-1);
  expect(to).toBeGreaterThan(from);
  const region = html.slice(from + START.length, to);
  // The region only depends on the global Math object.
  const factory = new Function(
    `${region}; return { STAGES, LEVELS_PER_STAGE, FORM_ORDER, LAYOUT_ORDER, LEVELS };`,
  );
  return factory() as {
    STAGES: Array<{ name: string; theme: string; boss: string; hasWater: boolean; hasLava: boolean }>;
    LEVELS_PER_STAGE: number;
    FORM_ORDER: string[];
    LAYOUT_ORDER: string[];
    LEVELS: Array<{
      form: string;
      theme: string;
      enemies: number;
      bossHp: number;
      eSpd: number;
      steps: number;
      hasWater: boolean;
      hasLava: boolean;
      boss: string;
      layout: string;
      stage: number;
    }>;
  };
}

describe('stage / level generation', () => {
  const { STAGES, LEVELS_PER_STAGE, FORM_ORDER, LAYOUT_ORDER, LEVELS } =
    extractGenerated();

  it('produces 10 stages of 10 levels = 100 levels', () => {
    expect(STAGES.length).toBe(10);
    expect(LEVELS_PER_STAGE).toBe(10);
    expect(LEVELS.length).toBe(STAGES.length * LEVELS_PER_STAGE);
    expect(LEVELS.length).toBe(100);
  });

  it('assigns every level to its parent stage in contiguous ranges', () => {
    LEVELS.forEach((lv, i) => {
      expect(lv.stage).toBe(Math.floor(i / LEVELS_PER_STAGE));
      expect(lv.theme).toBe(STAGES[lv.stage].theme);
      expect(lv.boss).toBe(STAGES[lv.stage].boss);
    });
  });

  it('only uses known layout archetypes and forms', () => {
    for (const lv of LEVELS) {
      expect(LAYOUT_ORDER).toContain(lv.layout);
      expect(FORM_ORDER).toContain(lv.form);
    }
  });

  it('ramps difficulty monotonically (non-decreasing) across all levels', () => {
    for (let i = 1; i < LEVELS.length; i++) {
      expect(LEVELS[i].enemies).toBeGreaterThanOrEqual(LEVELS[i - 1].enemies);
      expect(LEVELS[i].bossHp).toBeGreaterThanOrEqual(LEVELS[i - 1].bossHp);
      expect(LEVELS[i].eSpd).toBeGreaterThanOrEqual(LEVELS[i - 1].eSpd);
    }
  });

  it('keeps generated values within sane bounds', () => {
    for (const lv of LEVELS) {
      expect(lv.enemies).toBeGreaterThanOrEqual(6);
      expect(lv.bossHp).toBeGreaterThanOrEqual(3);
      expect(lv.eSpd).toBeGreaterThanOrEqual(1);
      expect(lv.steps).toBeGreaterThanOrEqual(4);
      expect(typeof lv.hasWater).toBe('boolean');
      expect(typeof lv.hasLava).toBe('boolean');
    }
  });

  it('varies layouts within each stage', () => {
    for (let s = 0; s < STAGES.length; s++) {
      const layouts = new Set(
        LEVELS.slice(s * LEVELS_PER_STAGE, (s + 1) * LEVELS_PER_STAGE).map(
          (lv) => lv.layout,
        ),
      );
      expect(layouts.size).toBeGreaterThan(1);
    }
  });
});
