"""A teacher dimension, so the availability table can be searched by NAME instead of by id.

WHY A DIMENSION AND NOT A COLUMN. `dbo.TeacherAvailabilities` deliberately stores no name — see the
entity: *"the name is display text that the dataset owns and can change; storing it here would
create a second, drifting copy of it in a table nobody would think to update."* That objection is
correct, and copying the name in would also leave a hole: rows written by the APP (`source='ui'`)
cannot populate a column the Rayfin entity does not declare, so they would show a blank name until
a seeder happened to re-run. Resolving the name at READ time through `dbo.vTeacherAvailability`
has neither problem — nothing drifts, and app-written rows get a name for free.

⚠️ THE NAMES ARE NOT REAL, AND NOT ALL UNREAL IN THE SAME WAY. Measured across the four datasets:

    oth / lmu   generated by the timetable generator   ("Prof. Dr. Q. Quirin")
    tum         INVENTED — TUMonline publishes no lecturer for a booking
    oth-real    Untis SHORT CODES, not names at all    ("Adee", "Akuc", and one literal "?")

A person's name is the most convincing thing on a screen, so `nameProvenance` is a column and not a
footnote: a reader querying this table by name must be able to see, in the same row, what kind of
thing they just matched on. This is the same rule `capacityProvenance` follows, and the same reason
`find_substitute` refuses outright when `store.teacher_attribution_invented` is set.

⚠️ NOT A RAYFIN ENTITY, ON PURPOSE. Created over TDS, exactly like the `teacher` column that was
added to `dbo.PlanAssignments`. That keeps it clear of `rayfin up db apply` (which 403s here) — but
it also means a rebuilt database will NOT have it until this script is run again.

    python tools/fabric/seed_teachers.py --dry-run
    python tools/fabric/seed_teachers.py
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(Path(__file__).resolve().parent))

import fabric_ids  # noqa: E402
import seed_plan_assignments as seed  # noqa: E402

SITES = {
    "oth": ROOT / "data" / "synthetic",
    "lmu": ROOT / "data" / "synthetic-lmu",
    "oth-real": ROOT / "data" / "oth-real",
    "tum": ROOT / "data" / "tum",
}

#: Used only where a row carries no provenance of its own. The generated datasets do not label
#: their people, because in those the whole timetable is generated — that IS the label.
DEFAULT_PROVENANCE = {"oth": "generated", "lmu": "generated"}

VIEW = "dbo.vTeacherAvailability"

CREATE_TABLE = """
IF OBJECT_ID('dbo.Teachers', 'U') IS NULL
CREATE TABLE dbo.Teachers (
    site            nvarchar(16)  NOT NULL,
    teacherId       nvarchar(64)  NOT NULL,
    name            nvarchar(200) NOT NULL,
    nameProvenance  nvarchar(80)  NOT NULL,
    facultyId       nvarchar(64)      NULL,
    contractSws     decimal(6,2)      NULL,
    CONSTRAINT PK_Teachers PRIMARY KEY (site, teacherId)
);
"""

# ⚠️ LEFT JOIN, NEVER INNER. An availability row whose teacher is missing from the dimension must
# still appear — with a NULL name that shows something is wrong. An inner join would delete it from
# the view silently, and every count taken from the view would be quietly short. This repository has
# been bitten by exactly that shape of bug before (three "silent" hubs, the vanished S-Bahn lines).
CREATE_VIEW = f"""
CREATE OR ALTER VIEW {VIEW} AS
SELECT
    a.id,
    a.site,
    a.teacherId,
    t.name           AS teacher,
    t.nameProvenance,
    t.facultyId,
    t.contractSws,
    a.slotId,
    a.state,
    a.source,
    a.note,
    a.updatedBy,
    a.updatedAt
FROM dbo.TeacherAvailabilities AS a
LEFT JOIN dbo.Teachers AS t
       ON t.site = a.site AND t.teacherId = a.teacherId;
"""


def rows_for(site: str) -> list[tuple]:
    folder = SITES[site]
    teachers = json.loads((folder / "teacher.json").read_text(encoding="utf-8"))
    out = []
    for t in teachers:
        provenance = (
            t.get("nameProvenance")
            or t.get("provenance")
            or DEFAULT_PROVENANCE.get(site, "unknown")
        )
        contract = t.get("contractSws")
        out.append((
            site,
            t["teacherId"],
            # A missing name falls back to the id rather than to an empty string: "unnamed" is a
            # fact worth seeing, and NOT NULL keeps the join column honest.
            t.get("name") or t["teacherId"],
            str(provenance)[:80],
            t.get("facultyId"),
            float(contract) if contract is not None else None,
        ))
    return out


def main() -> None:
    import pyodbc  # imported late so --help works without a driver

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--site", choices=sorted(SITES), help="only this site")
    parser.add_argument("--dry-run", action="store_true", help="report, write nothing")
    args = parser.parse_args()

    sites = [args.site] if args.site else sorted(SITES)
    planned = {s: rows_for(s) for s in sites}
    for s, rows in planned.items():
        kinds = sorted({r[3] for r in rows})
        print(f"{s:<10} {len(rows):>4} teachers   nameProvenance: {', '.join(kinds)}")
    if args.dry_run:
        print("\ndry run — nothing written")
        return

    with pyodbc.connect(
        f"Driver={{ODBC Driver 18 for SQL Server}};"
        f"Server={fabric_ids.sql_server()};Database={fabric_ids.sql_database()};"
        "Encrypt=yes;TrustServerCertificate=no;Connection Timeout=60",
        attrs_before={1256: seed.token()},
    ) as conn:
        cur = conn.cursor()
        cur.execute(CREATE_TABLE)

        for s, rows in planned.items():
            # Replace per site in one transaction. The dimension is derived wholly from the file,
            # so "delete this site then insert it" cannot leave a stale row behind — which is the
            # failure `verify_plan_assignments.py` exists to catch on the table that MERGEs.
            cur.execute("DELETE FROM dbo.Teachers WHERE site = ?", s)
            cur.executemany(
                "INSERT INTO dbo.Teachers "
                "(site, teacherId, name, nameProvenance, facultyId, contractSws) "
                "VALUES (?, ?, ?, ?, ?, ?)",
                rows,
            )
            print(f"  wrote {len(rows)} rows for {s}")

        cur.execute(CREATE_VIEW)
        conn.commit()

        # ── Prove the join actually resolves, rather than assuming it ───────────────────────
        cur.execute(f"SELECT COUNT(*) FROM {VIEW}")
        total = cur.fetchone()[0]
        cur.execute(f"SELECT COUNT(*) FROM {VIEW} WHERE teacher IS NULL")
        unresolved = cur.fetchone()[0]
        print(f"\n{VIEW}: {total} rows, {unresolved} without a name")
        if unresolved:
            cur.execute(
                f"SELECT TOP 5 site, teacherId, COUNT(*) FROM {VIEW} "
                "WHERE teacher IS NULL GROUP BY site, teacherId"
            )
            for site, tid, n in cur.fetchall():
                print(f"   unresolved: {site} {tid} ({n} rows)")


if __name__ == "__main__":
    main()
