#!/usr/bin/env python3
"""Generate the categorised app gallery in README.md from each app's own metadata.

Ported from the `generate-manifest.mjs` idea in awesome-rayfin PR #103. The point is
not a prettier table - it is that the index is DERIVED from `template.category` and
`template.displayName` in each app's package.json, so it cannot drift from the tree.
A hand-maintained list is wrong the first time somebody adds an app in a hurry.

  python tools/generate_index.py            rewrite the block in README.md
  python tools/generate_index.py --check     CI mode: exit 1 if README.md is stale
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
PREVIEWS = REPO / "docs" / "previews"
START = "<!-- APPS:START -->"
END = "<!-- APPS:END -->"
PLACEHOLDER = "docs/previews/_placeholder.webp"
PREVIEW_WIDTH = 220

CATEGORIES = [
    ("digital-twins", "🌍", "Digital Twins and Geospatial",
     "3D, map and live-operations views of real-world systems."),
    ("analytics", "📊", "Analytical Apps",
     "Apps that put data and insight in front of an end user."),
    ("fabric-tools", "🧰", "Fabric and Power BI Tools",
     "Apps that inspect, document or administer the data platform itself."),
    ("games", "🎮", "Games and Interactive Learning",
     "Canvas and game-engine apps — proof there is no UI ceiling."),
    ("starters", "🚀", "Starters",
     "Minimal scaffolds to build on."),
    ("business", "🏢", "Business Apps",
     "Everyday operational apps."),
    ("other", "📦", "More Apps",
     "Apps that have not picked a category yet."),
]
CATEGORY_DIRS = ["games-and-learn", "fabric-admin", "industry"]


def find_apps() -> list[dict]:
    apps: list[dict] = []

    def walk(folder: Path, depth: int = 0):
        if (folder / "package.json").exists():
            try:
                data = json.loads((folder / "package.json").read_text(encoding="utf-8"))
            except json.JSONDecodeError:
                return
            t = data.get("template") or {}
            rel = folder.relative_to(REPO).as_posix()
            apps.append({
                "path": rel,
                "slug": t.get("name") or folder.name,
                "display": t.get("displayName") or folder.name,
                "description": t.get("description") or "",
                "category": t.get("category") or "other",
                "wip": is_wip(folder),
            })
            return
        if depth >= 2:
            return
        for child in sorted(folder.iterdir()):
            if child.is_dir() and child.name not in {"node_modules", "dist"}:
                walk(child, depth + 1)

    for cat in CATEGORY_DIRS:
        base = REPO / cat
        if base.exists():
            walk(base)
    return apps


def is_wip(folder: Path) -> bool:
    rm = folder / "README.md"
    if not rm.exists():
        return False
    head = rm.read_text(encoding="utf-8", errors="replace").lstrip().splitlines()[:5]
    return any("work in progress" in ln.lower() for ln in head)


def preview_for(slug: str) -> str:
    for ext in ("webp", "png", "jpg", "gif"):
        p = PREVIEWS / f"{slug}.{ext}"
        if p.exists():
            return f"docs/previews/{slug}.{ext}"
    return PLACEHOLDER


def render(apps: list[dict]) -> str:
    out: list[str] = [START, ""]
    counts = {c[0]: [a for a in apps if a["category"] == c[0]] for c in CATEGORIES}
    present = [c for c in CATEGORIES if counts[c[0]]]

    out.append("**Jump to:** " + " · ".join(
        f"[{emoji} {title}](#{title.lower().replace(' ', '-').replace('and-', 'and-')})"
        for _id, emoji, title, _b in present))
    out.append("")

    for cid, emoji, title, blurb in present:
        rows = sorted(counts[cid], key=lambda a: a["display"].lower())
        out.append(f"### {emoji} {title}")
        out.append("")
        out.append(blurb)
        out.append("")
        out.append("| | App | What it does |")
        out.append("|---|---|---|")
        for a in rows:
            img = (f'<img src="{preview_for(a["slug"])}" width="{PREVIEW_WIDTH}" '
                   f'alt="{a["display"]} preview">')
            wip = " **`wip`**" if a["wip"] else ""
            out.append(f'| {img} | **[{a["display"]}]({a["path"]}/)**{wip} | {a["description"]} |')
        out.append("")

    out.append(f"*{len(apps)} apps. This table is generated by "
               f"`tools/generate_index.py` from each app's `package.json` — edit the app, "
               f"not the table.*")
    out.append("")
    out.append(END)
    return "\n".join(out)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    readme = REPO / "README.md"
    text = readme.read_text(encoding="utf-8")
    if START not in text or END not in text:
        print(f"README.md has no {START} / {END} block - add one first.")
        return 2

    before = text.split(START)[0]
    after = text.split(END)[1]
    new = before + render(find_apps()) + after

    if args.check:
        if new != text:
            print("README.md app gallery is out of date. Run: python tools/generate_index.py")
            return 1
        print("README.md app gallery is up to date")
        return 0

    if new == text:
        print("README.md already up to date")
        return 0
    readme.write_bytes(new.encode("utf-8"))
    apps = find_apps()
    by_cat: dict[str, int] = {}
    for a in apps:
        by_cat[a["category"]] = by_cat.get(a["category"], 0) + 1
    print(f"README.md regenerated - {len(apps)} apps: " +
          ", ".join(f"{k} {v}" for k, v in sorted(by_cat.items())))
    return 0


if __name__ == "__main__":
    sys.exit(main())
